# Generated by Django 4.1.3 on 2022-11-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('kat1', 'Kategoriya 1'), ('kat2', 'Kategoriya 2'), ('kat3', 'Kategoriya 3')], max_length=200)),
                ('currentNumber', models.IntegerField()),
                ('allNumber', models.IntegerField()),
                ('pubDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=400)),
                ('fakultet', models.CharField(max_length=400)),
                ('kurs', models.CharField(max_length=300)),
                ('profession', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=600)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('birthDate', models.DateField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.card')),
            ],
        ),
    ]
